language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_script:
script:
- npm run lint
after_success:
- npm publish
deploy:
  - provider: npm
    api_key: FvjPlzuYUWjr9OPqffsx8w
    on:
      branch: master
