language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_script:
script:
- npm run lint
after_success:
- npm publish
deploy:
  - provider: npm
    email: benedicte.rivalain@gmail.com
    api_key: dbac267d-a632-41cf-8bb9-3ac457950bce
    on:
      branch: master
